# Generated by Django 5.2.7 on 2025-10-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Сырой текст из Instagram')),
                ('edited_text', models.TextField(blank=True, null=True, verbose_name='Отредактированный текст')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Условия и дни проведения')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('published', 'Опубликовано'), ('deleted', 'Удалено')], default='moderation', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='establishments.establishment', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, verbose_name='Тип файла')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
            },
        ),
    ]
