# Generated by Django 5.2.7 on 2025-10-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('media_path', models.CharField(max_length=255)),
            ],
        ),
    ]
