# Generated by Django 5.2.7 on 2025-10-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя заведения')),
                ('instagram_url', models.URLField(unique=True, verbose_name='Ссылка на Instagram')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='locations.city', verbose_name='Город')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='categories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
    ]
